### ISSUE TITLE
Can't assume-role for longer than an hour (AWS limitation?)

### ISSUE THREAD

**Issue by davidham** [coinbase/assume-role#24] opened 2018-05-31 14:29 UTC
[**UPDATE**: This appears to be an AWS limitation? After many attempts with assume-role, and after recreating the issue using vanilla AWSCLI commands, it appears that you cannot assume a role for longer than an hour using temporary credentials generated with `aws sts get-session-token`. (See this [AWS forum thread](https://forums.aws.amazon.com/thread.jspa?threadID=242680) for more info. If anyone else is able to do this I'd be very grateful to know how you do it. Thanks!]

I set up assume-role as described in the README. I am attempting to assume a role IAMAdmin with user credentials on the same account. I am able to switch roles in the console, but when I try it with assume-role I get this error:

```
$ assume-role iam IAMAdmin 030460
Using assume-role default profile: iam

An error occurred (ValidationError) when calling the AssumeRole operation: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
Failed to export session envars.
```
I don't think I am doing role chaining--I am just trying to assume a role as a user. Any thoughts on why I'd see this?

UPDATE:
I was also able to assume the role by using the CLI directly:
```
$ aws sts assume-role --role-arn arn:aws:iam::000000000000:role/IAMAdmin --role-session-name testsession --profile iam --duration-seconds 43200 --serial-number arn:aws:iam:: 000000000000:mfa/David.Ham --token-code 994032
{
    "Credentials": {
        "AccessKeyId": "ASIAREDACTEDCITA",
        "SecretAccessKey": "eNA0yCXL0REDACTED",
        "SessionToken": "<REDACTED>",
        "Expiration": "2018-06-01T02:37:56Z"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "AROAJYQJREDACTED:testsession",
        "Arn": "arn:aws:sts:: 000000000000:assumed-role/IAMAdmin/testsession"
    }
}
```

**Comment by grahamjenson** [comment] 2018-05-31 15:08
I am not sure what the issue is here. The error being returned is from AWS so it probably a limitation put by amazon and not assume-role. 

In your example, it looks like you are assuming the role from your profiles user. assume-role first creates a session, then assumes the role from that session. Perhaps try both calls to replicate the issue, and if you find a solution please post here :).

P.S. redacted the session token from your issue.

**Comment by davidham** [comment] 2018-05-31 18:01
Thanks for the redact!

So I have several AWS profiles, and for this I was using a new user `David.Ham` on a new AWS account that I named `iam` in my AWS config profile. I ran this:
```
export AWS_PROFILE_ASSUME_ROLE="iam"
```
I did this to run all `assume-role` calls as this new, unprivileged user. So I don't _think_ I'm doing role chaining, but that's what the error is suggesting.

I'm excited to use this tool and approach, I'll let you know if I figure it out.

**Comment by davidham** [comment] 2018-06-01 15:05
Still no luck but here's the request with debug turned on:
```
$ DEBUG_ASSUME_ROLE=true assume-role iam
Using assume-role default profile: iam
Assume Into Role [read]: IAMAdmin
MFA Token: <REDACTED>
An error occurred (ValidationError) when calling the AssumeRole operation: The requested DurationSeconds exceeds the 1 hour session limit for roles assumed by role chaining.
Failed to export session envars.
AWS_CONFIG_REGION="us-east-1";
AWS_USERNAME="David.Ham";
MFA_DEVICE_ARGS="--user-name David.Ham --query MFADevices[0].SerialNumber --output text --profile iam";
MFA_DEVICE="arn:aws:iam::000000000000:mfa/David.Ham";
SESSION_ARGS="--duration-seconds 43200 --serial-number arn:aws:iam:: 000000000000:mfa/David.Ham --token-code 000000 --profile iam";
SESSION="{
    "Credentials": {
        "AccessKeyId": "<REDACTED>",
        "SecretAccessKey": "<REDACTED>",
        "SessionToken": "<REDACTED>",
        "Expiration": "2018-06-02T02:59:10Z"
    }
}";
ROLE_SESSION_ARGS="--role-arn arn:aws:iam::000000000000:role/IAMAdmin --external-id 000000000000 --duration-seconds 43199 --role-session-name 0000000000";
ROLE_SESSION="fail";
SESSION_TIMEOUT="43200";
ROLE_SESSION_TIMEOUT="43199";
AWS_PROFILE_ASSUME_ROLE="iam";
```
Does assume-role have to be into a separate account? For testing, I was trying an unprivileged user assuming a role in the same account.

**Comment by davidham** [comment] 2018-06-01 19:04
I also created a role to assume on another account, and I saw the same behavior. However, when I unset  `AWS_ROLE_SESSION_TIMEOUT` (I had tried it at 43200 and 43199), it works! Is this related to the `aws sts get-session-token` call? If you assume-role with the temporary credentials, does it count that as a "role," so that the subsequent call to `aws sts assume-role` thinks it is chained? Are you able to use `assume-role` with a `AWS_ROLE_SESSION_TIMEOUT` of greater than 3600?

**Comment by carlos-tovar** [comment] 2018-07-18 21:35
@davidham I am using a similar tool and ran into the same issue (cannot assume role with an expiration higher than 1 hour when using an MFA), so I went ahead and opened up a ticket with AWS.  They said this is a known issue and that it is an existing feature request.

**Comment by mf-lit** [comment] 2018-08-17 10:47
I'm seeing the same issue here (have spent a couple of hours trying to get it to work without success).
My accounts/roles/policies are setup exactly according to the Readme:
https://github.com/coinbase/assume-role#aws-bastion-account-setup
but I always get the `exceeds the 1 hour session limit for roles assumed by role chaining` error message.

I think the whole section in the Readme about setting AWS_ROLE_SESSION_TIMEOUT needs to be removed. It's completely misleading.

Tagging @brainstorm since he was the author of this. Hoping he has more insight?

**Comment by brainstorm** [comment] 2018-08-17 14:23
It works fine for us (using assume-role everyday). There's a setting on AWS to change the timeout from 1h to a maximum of 12h, I think it was under IAM->Roles.

**Comment by mf-lit** [comment] 2018-08-17 14:38
Really, that's so weird. I tried that setting but it makes no difference. Do you set up the bastion policy and account role as per the Readme too?

All the tests I've done corroborate with what @davidham describes above. It seems that the action of obtaining temporary credentials counts as using a role, so when the role in the target account is assumed, the 1 hour role-chaining limit is hit.

**Comment by eskp** [comment] 2019-08-19 02:32
@brainstorm even after setting the maximum duration in AWS console as you describe, by using temporary credentials with `assume-role`, it is considered as Role Chaining which is limited to 1 hour by AWS. Not sure how it can be working for you guys.

**Comment by brainstorm** [comment] 2019-08-19 02:59
We switched to [aws-google-auth](https://github.com/cevoaustralia/aws-google-auth) setup [with Google-based SSO](https://aws.amazon.com/blogs/security/how-to-set-up-federated-single-sign-on-to-aws-using-google-apps/) recently so not using `assume-role` anymore... but yeah @eskp you are probably right anyway.

**Comment by drewrothstein** [comment] 2020-01-19 21:42
Hi, we are closing out PRs + Issues as this project is being archived.

**Closed as completed by drewrothstein** 2020-01-19 21:42 UTC
